# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###
GET http://127.0.0.1:8000/model/create/model1
Accept: application/json

###
GET http://127.0.0.1:8000/model/fit/model1
Accept: application/json

###
GET http://127.0.0.1:8000/model/predict/model1
Accept: application/json


