# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###
GET http://127.0.0.1:8000/model/create/randomforest
Accept: application/json

###
GET http://127.0.0.1:8000/model/fit/randomforest
Accept: application/json

###
GET http://127.0.0.1:8000/model/predict/all/randomforest
Accept: application/json

###
POST http://127.0.0.1:8000/model/predict/randomforest
Accept: application/json
Content-Type: application/json

{
  "installment": 829.10,
  "log_annual_inc": 11.350407,
  "dti": 19.48,
  "fico": 737,
  "revol_bal": 28854,
  "revol_util": 52.1,
  "inq_last_6mths": 0,
  "delinq_2yrs": 0,
  "pub_rec": 0
}
